### ISSUE TITLE
amalgamation_ratio

### ISSUE THREAD

**Issue by zanejobe** [rgmyr/litholog#3]
I fixed an issue with net_to_gross to include both sand and gravel in the 'net' calculation. 

However, this needs to be fixed for amalgamation_ratio too, but we need to figure a way to look at either sand or gravel upper and lower contacts in an easy way. I messed around but didn't get far.

**Comment by rgmyr** [comment]
Hey @zanejobe, just noticed this issue. I'm reading that to mean "treat gravel as a sand", in which case this should be fixed in the latest commit. See [this line](https://github.com/rgmyr/litholog/blob/b48323493032423e724b0973fa8aee00171a1376/litholog/sequence/stats.py#L86) in stats.py.

The syntax works like:
```
>>> sand_like = ('sand', 'gravel')
>>> a = ('mud', 'gravel'); b = ('gravel', 'sand')
>>> [litho in sand_like for litho in a]
[False, True]
>>> [litho in sand_like for litho in b]
[True, True]
```
So if upper and lower are any combination of "sand-like", it will count as a `sand_contact`.

**Comment by zanejobe** [comment]
looks great! let's chat about depstrat soon ;)
